def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        // put here tools names as specified in Jenkins config
        maven "MAVEN3"
        jdk "OracleJDK8"
    }
    // Specify env variables used in settings.xml and pom.xml
    environment {
      cluster = 'staging' //create prod cluster and replace stage here 
      service = 'vpoappstagesvc'  //create prod cluster and put here

    }
    stages {
        
        stage('Deploy to ECS PROD') {
            steps {
                withAWS(credentials: 'awscreds', region: 'eu-central-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
        post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#jenkins_cicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}